Repository Aifred-Health/Vulcan, pull requests merged in 2018-12, with the labels that each got.

#96 Weight bias init update
  examples/fashion_conv_dense_test.py
  vulcanai2/models/layers.py
  vulcanai2/models/utils.py
  vulcanai2/tests/models/test_layers.py
Labels: ReviewReady, bug fix, enhancement

#101 Dataset improvements and tests
  vulcanai2/__init__.py
  vulcanai2/datasets/fashion.py
  vulcanai2/datasets/tabulardataset.py
  vulcanai2/datasets/utils.py
  vulcanai2/log.ini
  vulcanai2/tests/datasets/test_data/birthweight_reduced.csv
  vulcanai2/tests/datasets/test_data/birthweight_reduced2.csv
  vulcanai2/tests/datasets/test_data/birthweight_reduced_merged.csv
  vulcanai2/tests/datasets/test_fashion.py
  vulcanai2/tests/datasets/test_tabulardataset.py
  vulcanai2/tests/datasets/test_utils.py
Labels: ReviewReady

#102 TESTS
  .gitignore
  vulcanai2/models/basenetwork.py
  vulcanai2/models/cnn.py
  vulcanai2/models/dnn.py
  vulcanai2/models/layers.py
  vulcanai2/models/metrics.py
  vulcanai2/models/utils.py
  vulcanai2/plotters/visualization.py
  vulcanai2/tests/models/__init__.py
  vulcanai2/tests/models/conftest.py
  vulcanai2/tests/models/test_basenetwork.py
  vulcanai2/tests/models/test_cnn.py
  vulcanai2/tests/models/test_device.py
  vulcanai2/tests/models/test_dnn.py
  vulcanai2/tests/models/test_ensemble.py
  vulcanai2/tests/models/test_layers.py
  vulcanai2/tests/models/test_metrics.py
  vulcanai2/tests/models/test_utils.py
  vulcanai2/tests/plotters/test_visualization.py
Labels: bug fix, enhancement
